server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos?createDatabaseIfNotExist=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari.maximum-pooll-size: 10
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: restaurante
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.zcoders.restaurante.listener.NovoPedidoDeserializer
      topic:
        novo-pedido: PEDIDO_NOVO
        pedido-cancelado: PEDIDO_CANCELADO

  kafka1:
    consumer:
      bootstrap-servers: 127.0.0.1:9093
      group-id: conta
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.zcoders.oferta.listener.NovaContaDeserializer
      topic:
        nova-conta: NOVA_CONTA

  kafka2:
    consumer:
      bootstrap-servers: 127.0.0.1:9094
      group-id: livraria
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.zcoders.notificacao.listener.NovaVendaDeserializer
      topic:
        nova-venda: NOVA_VENDA