version: '3'
services:
  postgres:
    image: postgres:9.6
    hostname: postgres
    domainname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pedidos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root